title:              Larry Saavedra
email:              saavedra.larry@gmail.com
description:        MS Analytics Student at Georgia Tech
author:             Larry Saavedra
baseurl:            ""
url:                "https://LarryS19.github.io"

# Social Profiles
twitter_username:   
github_username:    LarryS19
facebook_username:
instagram_username:  
linkedin_username:  l-saavedra

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
